MNPContactManagementWeb/Models/ContactDetails.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MNPContactManagementWeb.Models
{
    public class ContactDetails
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-.●]?([0-9]{3})[-.●]?([0-9]{4})$", ErrorMessage = "The format of Phone is XXX-XXX-XXXX")]
        public string? Phone { get; set; }
        public string? Address { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Last Date Contacted")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime? LastDateContacted { get; set; } = DateTime.Now;
        [DisplayName("Job Title")]
        public string JobTitle { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string? Comments { get; set; }
    }
}

MNPContactManagementWeb/Models/ErrorViewModel.cs
namespace MNPContactManagementWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MNPContactManagementWeb/Controllers/ContactDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using MNPContactManagementWeb.Data;
using MNPContactManagementWeb.Models;

namespace MNPContactManagementWeb.Controllers
{
    public class ContactDetailsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ContactDetailsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ContactDetails> objContactList = _db.ContactDetails;
            return View(objContactList);
        }

        public IActionResult Create()
        {
            
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ContactDetails contactDetails)
        {
            
            if(ModelState.IsValid)
            {
                _db.ContactDetails.Add(contactDetails);
                _db.SaveChanges();
                TempData["success"] = "Contact Added Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id==null || id == 0)
            {
                return NotFound();
            }
            var ContactDetails = _db.ContactDetails.Find(id);
            if (ContactDetails == null)
            {
                return NotFound();
            }
            return View(ContactDetails);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ContactDetails contactDetails)
        {

            if (ModelState.IsValid)
            {
                _db.ContactDetails.Update(contactDetails);
                _db.SaveChanges();
                TempData["success"] = "Contact Updated Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

MNPContactManagementWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MNPContactManagementWeb.Models;
using System.Diagnostics;

namespace MNPContactManagementWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MNPContactManagementWeb/Views/ContactDetails/Create.cshtml
@model ContactDetails

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create New Contact</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="container">
            <div class="row">
                <div class="col-sm">
                     <label asp-for="Name"></label>
                     <input asp-for="Name" class="frm-control" maxlength="100" />
                </div>
                <div class="col-sm">
                     <label asp-for="Address"></label>
                     <input asp-for="Address" class="frm-control" maxlength="150" />
                </div>
                 <div class="col-sm">
                      <label asp-for="LastDateContacted">Last Date Contacted</label>
                      <input type="datetime" id="datepicker" asp-for="LastDateContacted" class="frm-control"  value="@DateTime.Now.ToString("yyyy-MM-ddThh:mm")"/>
                </div>
            </div>
        </div>
    
    <div class="container">
        <div class="row">
             <div class="col-sm">
                      <label asp-for="JobTitle">Job Title</label>
                      <input asp-for="JobTitle" class="frm-control" maxlength="50" />
                </div>
                <div class="col-sm">
                     <label asp-for="Phone"></label>
                     <input asp-for="Phone" class="frm-control" />
                </div>
                <div class="col-sm">
                      <label style="display:none;" asp-for="LastDateContacted">Last Date Contacted</label>
                      <input style="display:none;" type="datetime" id="datepicker" asp-for="LastDateContacted" class="frm-control"  value="@DateTime.Now.ToString("yyyy-MM-ddThh:mm")"/>
                </div>
        </div>
    </div>

     <div class="container">
            <div class="row">
                <div class="col-sm">
                     <label asp-for="Company"></label>
                    <select asp-for="Company" class="frm-control">
                        <option>Disney</option>
                        <option>HP</option>
                        <option>Microsoft</option>
                    </select>
                </div>
                <div class="col-sm">
                      <label asp-for="Email"></label>
                      <input type="email" asp-for="Email" class="frm-control" maxlength="100" />
        
                </div>
                 <div class="col-sm">
                       <label asp-for="Comments"></label>
                       <textarea asp-for="Comments" maxlength="1000" class="frm-cotrol"></textarea>
                </div>
            </div>
        </div>
   <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
   <a asp-controller="ContactDetails" asp-action="Index" class="btn btn-secondary" style="width:150px">Cancel</a>
    </div>
</form>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
     <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
}
}

MNPContactManagementWeb/Views/ContactDetails/Edit.cshtml
@model ContactDetails

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Contact</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="container">
            <div class="row">
                <div class="col-sm">
                     <label asp-for="Name"></label>
                     <input asp-for="Name" class="frm-control" maxlength="100"  />
                </div>
                <div class="col-sm">
                     <label asp-for="Address"></label>
                     <input asp-for="Address" class="frm-control" maxlength="150" />
                </div>
                 <div class="col-sm">
                      <label asp-for="LastDateContacted">Last Date Contacted</label>
                      <input type="datetime" id="datepicker" asp-for="LastDateContacted" class="frm-control"  value="@DateTime.Now.ToString("yyyy-MM-ddThh:mm")"/>
                </div>
            </div>
        </div>
    
    <div class="container">
        <div class="row">
             <div class="col-sm">
                      <label asp-for="JobTitle">Job Title</label>
                      <input asp-for="JobTitle" class="frm-control" maxlength="50"/>
                </div>
                <div class="col-sm">
                     <label asp-for="Phone"></label>
                     <input asp-for="Phone" class="frm-control" />
                </div>
                <div class="col-sm">
                      <label style="display:none;" asp-for="LastDateContacted">Last Date Contacted</label>
                      <input style="display:none;" type="datetime" asp-for="LastDateContacted" class="frm-control" />
                </div>
        </div>
    </div>

     <div class="container">
            <div class="row">
                <div class="col-sm">
                     <label asp-for="Company"></label>
                    <select asp-for="Company" class="frm-control">
                        <option>Disney</option>
                        <option>HP</option>
                        <option>Microsoft</option>
                    </select>
                </div>
                <div class="col-sm">
                      <label asp-for="Email"></label>
                      <input type="email" asp-for="Email" class="frm-control" maxlength="100"/>
                </div>
                 <div class="col-sm">
                       <label asp-for="Comments"></label>
                       <textarea asp-for="Comments" maxlength="1000" class="frm-cotrol"></textarea>
                </div>
            </div>
        </div>
   <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
   <a asp-controller="ContactDetails" asp-action="Index" class="btn btn-secondary" style="width:150px">Cancel</a>
    </div>
</form>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
     <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
}
}

MNPContactManagementWeb/Views/ContactDetails/Index.cshtml
@model IEnumerable<ContactDetails>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />

<h1>Contact Details</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Contact List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ContactDetails" asp-action="Create" class="btn btn-primary">Create New Contact</a>
        </div>
    </div>


<table class="table table-bordered table-stripped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
                (job title)
            </th>
            <th>
                Company
            </th>
            <th>
                Phone
            </th>
            <th>
                Address
            </th>
            <th>
                Email
            </th>
            <th>
                Last Date Contacted
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.Name (@obj.JobTitle)
                </td>
                <td>
                    @obj.Company
                </td>
                <td>
                    @obj.Phone
                </td>
                <td>
                    @obj.Address
                </td>
                <td>
                    @obj.Email
                </td>
                <td>
                    @obj.LastDateContacted
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ContactDetails" asp-action="Edit" asp-route-id=@obj.Id><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>

</table>
</div>

MNPContactManagementWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to MNP Contact Management. Please click on Contact Details on the Navigation Bar to view the list of contacts and other operations.</h1>
</div>

MNPContactManagementWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MNPContactManagementWeb</title>
    <link rel="stylesheet" href="~/css/BootSwatchTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MNPContactManagementWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MNP Contact Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
         <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="ContactDetails" asp-action="Index">Contact Details</a>
        </li>
    </div>
  </div>
</nav>
 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - MNPContactManagementWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MNPContactManagementWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}